### ISSUE TITLE
This will not work with SSR?

### ISSUE THREAD

**Issue by canyoudev** [matsp/material-components-vue#102]
Am I getting this right - there's no chance to make this package work with SSR/Nuxt?

**Comment by matsp** [comment]
What are the requirements for nuxt? I didn't work on SSR yet but   it should be possible to render the components on server side.

**Comment by matsp** [comment]
After checking the SSR docs I can't find a point that the components shouldn't work with server side rendering.

**Comment by matsp** [comment]
@canyoudev You need this issue anymore? If you have something to contribute to this project feel free to send pull requests :)
