### ISSUE TITLE
[QUESTION] importing 1 button increases vendors.js file size by ~ 85kb

### ISSUE THREAD

**Issue by joebartels** [matsp/material-components-vue#125]
Hey, another question 😄 
```bash
npx vue --version
3.0.0-beta.16
```

When adding a button like so:
```js
// main.js
import MaterialButton from 'material-components-vue/dist/button';
Vue.use(MaterialButton);
```

Before importing the button:
```bash
  dist/js/chunk-vendors.02da9ab1.js    107.60 kb          37.21 kb
  dist/js/app.23deb2c8.js              5.70 kb            1.91 kb
  dist/css/app.1982d636.css            42.30 kb           6.71 kb
```
After:
```bash
  dist/js/chunk-vendors.584056db.js    192.74 kb          53.25 kb
  dist/js/app.2fde2bab.js              5.71 kb            1.95 kb
  dist/css/app.40d5fb4c.css            53.08 kb           8.04 kb
```

**+85kb**  on build (`npm run build production`):

I don't know if this is caused _by_ this plugin or is a vue configuration issue.

It's a fresh project (`vue create some-project`)with no other plugins.

It appears that the additional fluff comes from a ton of comments like this:
```
/*!**************************************************!*\
  !*** ./node_modules/@material/base/component.js ***!
  \**************************************************/
/*! exports provided: default */function(module,__webpack_exports__,__ ...

/*!**************************************************!*\
  !*** ./node_modules/@material/ripple/adapter.js ***!
  \**************************************************/
/*! exports provided: default */function(module,__webpack_exports__,__w ...
```

---

Upon inspecting the webpack config (`npx vue inspect > output.js --mode production`)
It appears that the `uglifyOptions` is this:
```
uglifyOptions: {
  output: {
    comments: /^\**!|@preserve|@license|@cc_on/
  },
```

which seem to indicate that all these `/*!` comments should be preserved but some of the `/*!` prefixed comments seem legit (like license etc.)

e.g. this looks legit and I'm okay with keeping it in production build:
```
/*!
 * Vue.js v2.5.16
 * (c) 2014-2018 Evan You
 * Released under the MIT License.
 */
```

Any thoughts or recommendations for reducing build size???

**Comment by joebartels** [comment]
O cool. that helps.

Importing the minified does bring file size down from **192.74 kb** to **133.46 kb**
```
import MaterialButton from 'material-components-vue/dist/button/button.min';
```
This still seems like a lot of **kb** for a button... but that's probably on material-components-web at that point?

**Comment by joebartels** [comment]
true. the gzip size is very reasonable although I'm toying with building a chrome extension so I'm not concerned with optimizing the file sizes over-the-wire and more so with keeping a small footprint overall.

I wonder if it can be remedied through the webpack config in this repo?
idk webpack good enough yet to be helpful 😞 - just thinking "out loud".

**Comment by matsp** [comment]
There is not much left to optimize. Webpack is running in the right modes, which activates the right plugins for production and development. When Babel 7 documentation is more complete maybe we can save a few KiB more e.g. removing all comments. Dropping IE support will also improve the result, but I sadly need that at a project at work ..
