### ISSUE TITLE
Icon Button hangs Chrome mobile and Firefox (at least)

### ISSUE THREAD

**Issue by ticamacho** [matsp/material-components-vue#132]
Since the migration to the icon-button (from icon-toggle) I've noted some issues using this component on Chrome (mobile) and Firefox (latest desktop on OS X).

When clicking the button, it hangs the browser. I'm using the component passing the toggle-on-content and toggle-off-content props.

I've been testing directly with the material framework, and the culprit seems to be the update() callback that is being called by the MutationObserver. When this method is called, it hangs the browser.

**Comment by matsp** [comment]
@ticamacho 

Thanks for filling the issue! Can you please provide a reproduction.

**Comment by matsp** [comment]
I could reproduce the issue. It's the ripple effect that cause the freezes.

**Comment by ticamacho** [comment]
@matsp 

Sorry for the delay. Yes, the ripple effect seems to be the culprit. Thanks for the quick fix.
