### ISSUE TITLE
typescript support ?

### ISSUE THREAD

**Issue by gedw99** [matsp/material-components-vue#136]
Vue officially has Typescript support. Its here:
https://vuejs.org/v2/guide/typescript.html

Is it easy to also support it with this this project as it would make things easier

**Comment by matsp** [comment]
@gedw99

Thanks for filling the issue.
I am not very familiar with Typescript, just played a little bit years ago. I think it's possible to support but I actually don't have the time to additionally do that, but you can open a feature request issue and will at least analyse what needs to be done for it.

**Comment by gedw99** [comment]
I don't have time.

**Comment by matsp** [comment]
Mhm okay. Thanks anyway.
