### ISSUE TITLE
Textfield - Update label position when value is added in an empty textfield

### ISSUE THREAD

**Issue by muffeen** [matsp/material-components-vue#140]
Related issue:
https://github.com/material-components/material-components-web/issues/822

**Comment by matsp** [comment]
Thanks for filling the issue, the fix will be integrated after the next mdc-web release.

**Comment by muffeen** [comment]
Great! Will be looking forward to the next release. Thanks :)

**Comment by JurajVajda** [comment]
same issue here still appearing any update on this ? thanks
