### ISSUE TITLE
m-notched-outline not working with m-select

### ISSUE THREAD

**Issue by e-oj** [matsp/material-components-vue#149]
Great job with this library. I'm trying to use notched outline with the select component but it's not working.

**To Reproduce**
```html
<m-select outlined v-model="address.city" id="city-settings">
   <option :key="'rochester'" :value="'Rochester'">Rochester</option>

   <m-floating-label slot="label">
     City
   </m-floating-label>

   <m-notched-outline slot="line"></m-notched-outline>
</m-select>
```

**Expected behavior**
Should behave like the [outlined select example](https://material-components.github.io/material-components-web-catalog/#/component/select)

**Screenshots**
Does this instead
<img width="140" alt="screen shot 2018-08-14 at 8 27 13 pm" src="https://user-images.githubusercontent.com/9700116/44113610-923b8d6a-a000-11e8-962b-2a7c05d5fb5b.png">

Any help would be appreciated

**Comment by matsp** [comment]
Thanks for filling this issue.

The arrow issue could be resolved with postcss/autoprefixer or manual adding '-webkit-appearance: none;' to the CSS class.

You imported the notched-outline component correctly? Can you see it in the DOM?

**Comment by e-oj** [comment]
I can't see it in the DOM. The notched outline component is imported correctly though; I'm using it successfully on textfields in the same form.

**Comment by matsp** [comment]
At least the js instantion is missing. I have to investigate why it is working on the textfield.

**Comment by e-oj** [comment]
**JS imports**
<img width="567" alt="screen shot 2018-08-14 at 9 53 56 pm" src="https://user-images.githubusercontent.com/9700116/44117931-927635a8-a00c-11e8-8a2d-bd96a896ec5f.png">

**Style Imports**
<img width="664" alt="screen shot 2018-08-14 at 9 55 25 pm" src="https://user-images.githubusercontent.com/9700116/44118103-fb50facc-a00c-11e8-83e0-ecf0d4c9c7e7.png">

**Comment by matsp** [comment]
I meant on the component side. Think your code is okay.

**Comment by e-oj** [comment]
Oh. Alright.

**Comment by matsp** [comment]
@e-oj 
Can you upgrade to version 0.26.0 and have a look if it fixed your issue?

**Comment by e-oj** [comment]
Yes it does. Thanks 👍 👍

**Comment by matsp** [comment]
Thanks for testing :ok_hand:
