### ISSUE TITLE
Update mdc-web to 0.38.2

### ISSUE THREAD

**Issue by matsp** [matsp/material-components-vue#158]
This include the versions 0.38.0 and 0.38.1: [Changelog mdc-web](https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#0380-2018-07-30)

Needed changes can be found in Features and Breaking Changes of the changelog.

**Comment by Kolhar730** [comment]
How do I contribute here? What exactly is expected of me here?

**Comment by matsp** [comment]
@Kolhar730 This projects relies on the upstream google project [mdc-web](https://github.com/material-components/material-components-web). So every release in mdc-web has to be implemented or adapted in this project. There is a small section in contrution guidelines how to do upgrade to new versions. Do you have some experience from earlier js/npm projects?

**Comment by Kolhar730** [comment]
#160 here's what I've done. let me know if there are changes to be done.

**Comment by rchan** [comment]
@matsp #176 contains the fixes for the breaking changes around List, Switch and Tabbar, other breaking changes does not affect
