### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by raybog** [matsp/material-components-vue#159]
Is it possible to use `material-components-vue` in Vue Type Script project?

**Comment by Kolhar730** [comment]
Vue has added Typescript support from Vue 2.5 onwards. If you're interested in knowing how you can use TypeScript in your project the details can be found [here](https://vuejs.org/v2/guide/typescript.html). Also, there was another issue previously #136 and @matsp clarified that the support would be added in the near future. But this issue shall remain open for the time being.

**Comment by matsp** [comment]
Like @Kolhar730 said, you can use Typescript but this project has actually no type definitions.
