### ISSUE TITLE
Drawer README not showing example code

### ISSUE THREAD

**Issue by johnhorsema** [matsp/material-components-vue#218]
**Describe the bug**
No example is shown for using drawer in the README.md file.

https://github.com/matsp/material-components-vue/blob/master/components/drawer/README.md

**Comment by tychenjiajun** [comment]
Due to the enormous workload, I can't keep the docs in sync with changes in the code.

You can check https://github.com/matsp/material-components-vue/tree/master/docs/.vuepress/components/drawer for demos. Pull requests on docs are welcomed.

**Comment by johnhorsema** [comment]
@tychenjiajun I can offer to complete some of the docs as I go with my project so that others can pick up this library faster.

**Comment by tychenjiajun** [comment]
fixed in #381
