### ISSUE TITLE
Menu - first item is always being auto focused

### ISSUE THREAD

**Issue by kfirba** [matsp/material-components-vue#220]
**Is your feature request related to a problem? Please describe.**
The menu component always autofocuses on the first item in the list. The `menu` element also exposes a [`setDefaultFocusItemIndex`](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/README.md#mdcmenu-properties-and-methods) method which let us manually choose which element is auto-focused when the menu is opened.

**Describe the solution you'd like**
Adding a new  `focusedIndex` property on the `Menu.vue` component that defaults to `0` (for BC) which calls the `setDefaultFocusItemIndex` method each time the menu is opened (or watch the `focusedIndex` property and call the `setDefaultFocusItemIndex` method each time it changes).

**Comment by tychenjiajun** [comment]
Is it `setDefaultFocusState`?

**Comment by kfirba** [comment]
@tychenjiajun Not sure what is it you are asking?

**Comment by matsp** [comment]
When I saw that correctly it's not released yet.

**Comment by tychenjiajun** [comment]
@kfirba The readme in mdc-menu is not so clear and I only saw `setDefaultFocusState` and it has four states according to the [source code](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/constants.ts)

**Comment by kfirba** [comment]
@matsp You are right. It hasn't been released yet, unfortunately.

@tychenjiajun I see what you mean! Sorry, didn't notice it was not released yet. By the way, how do I set the `DefaultFocusState` to `NONE`?

**Comment by tychenjiajun** [comment]
@kfirba A new property `focusState` should be added to the `Menu.vue` component, just like the `anchorCorner`.

**Comment by kfirba** [comment]
@tychenjiajun I see. Is it something that is in under development or is a PR required?

cc @matsp

**Comment by tychenjiajun** [comment]
@kfirba I'm not activly developing it so a PR will be grateful.

**Comment by kfirba** [comment]
@tychenjiajun Unfortunately, this is also not yet released

**Comment by tychenjiajun** [comment]
@kfirba So we have to wait and see which method, `setDefaultFocusState` or `setDefaultFocusItemIndex` will be released in the next version of mdc-web. I'll keep an eye on it and comment here once the mdc-web has anything updated.

**Comment by tychenjiajun** [comment]
@kfirba It's released now in a major version. But we have to check if other components will be influenced before upgrading mdc-web

**Comment by kfirba** [comment]
@tychenjiajun Okay, I'll close this issue in favor for a new issue where we discuss the upgrade to mdc-web 2.0
