### ISSUE TITLE
Enhanced select's isn't firing model updates

### ISSUE THREAD

**Issue by MajorError** [matsp/material-components-vue#233]
**Describe the bug**
Very impressed with this project - it's been hugely helpful in my Material/Vue integration and learning path!

I'm trying to use the Enhanced select (as per https://github.com/material-components/material-components-web/tree/master/packages/mdc-select#enhanced-select). It appears that it's supported in this binding, if undocumented (https://github.com/matsp/material-components-vue/blob/master/components/select/Select.vue#L12) - not sure if this implies that the binding is incomplete for this feature, or if I'm just writing the wrong incantations. When I use the enhanced model, I have to use `<m-list-item />` tags to make the menu render correctly, but these don't appear to be firing model update events (I'm using the Vue debug extension in Chrome to inspect this).

If you're able to offer any guidance on where I'm going wrong, or an indicator if this is expected behaviour and needs a patch to `Select.vue` to support, I'd be very grateful! I'm relatively new to Vue, but happy to attempt a PR if it's the latter.

**To Reproduce**
```
      <m-form-field>
        <m-select enhanced v-model="modelField" id="selectName">
          <m-list-item
            v-for="option in [{text: 'None', value: 'NONE'},
                              {text: 'Primary', value: 'primary-value'},
                              {text: 'Secondary', value: 'secondary-value'},
                              {text: 'Tertiary', value: 'tertiary-value'}]"
            :name="option.value"
            :data-value="option.value">
            {{ option.text }}
          </m-list-item>
          <m-floating-label slot="label">Caption</m-floating-label>
          <m-line-ripple slot="line"></m-line-ripple>
        </m-select>
      </m-form-field>
```

**Expected behavior**
When the user clicks an element in the menu, the model field `modelField` should update.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2
 - Browser Chrome
 - Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by tychenjiajun** [comment]
Thank you for your reporting. The issue will be fixed here. https://github.com/matsp/material-components-vue/pull/232

**Comment by MajorError** [comment]
Whoops, my bad - I checked issues but not open PRs.

Thank you for such a prompt response, Jiajun. Keep up the excellent work!

For anyone stumbling across this issue in the meantime, I've made a temporary patch to my code (to save me from rebuilding material-components-vue) to add a `click` binding to each `m-list-item` to update the model:

```
          <m-list-item
            v-for="option in [{text: 'None', value: 'NONE'},
                              {text: 'Primary', value: 'primary-value'},
                              {text: 'Secondary', value: 'secondary-value'},
                              {text: 'Tertiary', value: 'tertiary-value'}]"
            :name="option.value"
            :data-value="option.value"
            @click="modelField = option.value">
            {{ option.text }}
          </m-list-item>
```

I look forward to replacing this when #232 is merged and released.

**Comment by matsp** [comment]
fixed in v1.0.0

**Comment by MajorError** [comment]
Great to see the fix merged so fast, thanks folks! I'm unable to get this to work still, however, after updating my version of `material-components-vue` from npm. I can see the `MDCSelect` is updating its state correctly (I have added the `name` prop so that I get a hidden `<input />`, which has the correct value as I select options from the list). However, the `<m-select />`'s `$attrs.value` that is shown in the Vue devtools never changes to reflect this (and consequently the `v-model` isn't updated accordingly). 

I'm probably missing something obvious, so my apologies for bugging you!

**Comment by matsp** [comment]
@tychenjiajun Can you have a look at this?

**Comment by tychenjiajun** [comment]
@MajorError @matsp My bad. Looking at it.

**Comment by tychenjiajun** [comment]
@MajorError Check the codepen here https://codepen.io/chankcccc/pen/QRGjZa . It seems to be working well.

**Comment by tychenjiajun** [comment]
@MajorError It seems like a building issue. I'll open a new issue describing it.

**Comment by MajorError** [comment]
Thanks, @tychenjiajun - you're right that it seems to work in the codepen above. I'm trying to compare what I've got and what's in the pen, to see at what point I can make the two converge!

**Comment by matsp** [comment]
fixed in v1.0.2

**Comment by MajorError** [comment]
That's outstanding work chaps - thank you so much for everything!

Confirmed as working in my environment too.

**Comment by tychenjiajun** [comment]
@MajorError  And now you can also add event handler for `change` event to get the selected index. 
Due to huge daily workload, docs in most components are outdated. We'll be grateful if you could help :)
