### ISSUE TITLE
No index.js in every component in 1.0.1 released.

### ISSUE THREAD

**Issue by tychenjiajun** [matsp/material-components-vue#236]
**Describe the bug**
No index.js in every component in 1.0.1 released.

**To Reproduce**
1. See https://unpkg.com/material-components-vue@1.0.1/dist/button/ and https://unpkg.com/material-components-vue@1.0.0/dist/button/
2. Compare the files.

**Expected behavior**
There should be an index.js for every component to be imported as a module.

**Comment by matsp** [comment]
uuups

**Comment by matsp** [comment]
fixed in v1.0.2
