### ISSUE TITLE
Define ripple as a mixin, instead of a component

### ISSUE THREAD

**Issue by tychenjiajun** [matsp/material-components-vue#267]
**Is your feature request related to a problem? Please describe.**
When using `m-ripple` component to provide custom components with a ripple effect, there's an extra unnecessary div parent element for my custom components.

**Describe the solution you'd like**
Define ripple as a mixin. In this way, users who implement their custom components can easily mix the ripple effect into their custom components by adding the ripple mixin.

**Comment by tychenjiajun** [comment]
Sorry for bothering you @matsp, do you have any idea?

**Comment by matsp** [comment]
@tychenjiajun sorry Iam actually moving to another country and have not much time.

**Comment by matsp** [comment]
@tychenjiajun I think I had or wanted to implement the ripple effect as a mixin but I am not sure why I give up on that. Maybe you find it out when you implement it.
