### ISSUE TITLE
Tab v-model not updating

### ISSUE THREAD

**Issue by MajorError** [matsp/material-components-vue#281]
**Describe the bug**
As tabs are activated in a tab bar, their `v-model` isn't updating to reflect the tab state. They appear to listen to model updates correctly, but the `active` prop doesn't update when the tab is activated, so they never update the model.

**To Reproduce**
https://codepen.io/anon/pen/MddGpr 
(based on https://github.com/matsp/material-components-vue/blob/master/docs/.vuepress/components/TabsDemo.vue)

**Expected behavior**
As tabs are selected, their bound `v-model` should update (in the case of the codepen above, I would expect the state of `tabs` to mutate)

**Comment by MajorError** [comment]
I should add, I've not forgotten your suggestion that I contribute to updating the docs - I'd love to, once I'm out from under a few deadlines. I definitely empathise with your workload constraints, and am extremely grateful for your support!

**Comment by tychenjiajun** [comment]
I faced the same issue when I was updating the whole project to `1.0.0` version. I post an issue about it in https://github.com/material-components/material-components-web/issues/4505

**Comment by MajorError** [comment]
This is useful, thanks for the pointer. It's a shame to see that the developers consider the use case out of scope. Does https://codepen.io/anon/pen/ZNNqWw seem like the best way to work around this (it's akin to https://github.com/material-components/material-components-web/issues/4505#issuecomment-473065096 I think)?

**Comment by tychenjiajun** [comment]
I believe there's still possible to use `v-model`, I've already have some possible solutions in my mind.

**Comment by tychenjiajun** [comment]
A possible solution is to use something like `MutationObserver` to 'observe' the class change. Another possible solution is to listen to the `MDCTab: interacted` event. It's nighttime in China now, I'll fix it tomorrow.
If you can handle it, pull request is welcomed.
