### ISSUE TITLE
Snackbar: TypeError: Cannot set property 'textContent' of null

### ISSUE THREAD

**Issue by lucatescari** [matsp/material-components-vue#297]
**Describe the bug**
When creating a <m-snackbar /> I get a console error in the browser 'TypeError: Cannot set property 'textContent' of null'. The Snackbar still seems to work fine though (including text).

**To Reproduce**
1. Create a <m-snackbar />
2. run
3. open in browser
4. open console
5. see error

**Expected behavior**
There should not be an error (unless it's a mistake on my side).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 74

**Comment by tychenjiajun** [comment]
Could you please paste your code here or paste a link to codepen ([here is an example](https://codepen.io/chankcccc/pen/LKWPNr))?

**Comment by lucatescari** [comment]
Hi, Thanks for the quick response!
Thanks to your CodePen I just found out that this happens when you don't add the attribute 'action-button-text'. Is there a way to not use an action button in a snackbar?

**Comment by tychenjiajun** [comment]
@lucatescari It seems that this issue is fixed in #256 but it's not released yet.

**Comment by lucatescari** [comment]
Ah okay no problem, I could not find the original issue. 
In this case I will work around it and wait for the release.
