### ISSUE TITLE
[m-tab-bar] Errors after switching

### ISSUE THREAD

**Issue by antivitla** [matsp/material-components-vue#312]
**Describe the bug**
Console errors with `m-tab-bar`, possibly preventing from getting events from it.

**To Reproduce**
Reproducible on Codepen: https://codepen.io/antivitla/pen/qzVRwY
Try to switch tabs, check appearing console errors including 'Cannot read property 'getScrollPosition' of null"' and others inside material-components.

**Screenshots**
Screen from codepen: 
![Desktop-screenshot (1)](https://user-images.githubusercontent.com/2784490/60265318-257b8080-98ee-11e9-8461-c72935b83b5f.png)

Better errors when trying to import by module, this way error is happening inside MDCTabBar component code: 
![Desktop-screenshot](https://user-images.githubusercontent.com/2784490/60265366-404df500-98ee-11e9-8156-1922dc83ae07.png)

**Desktop (please complete the following information):**
 - Windows 10, Chrome latest

**Comment by tychenjiajun** [comment]
Add a scroller and it will be fine **https://codepen.io/anon/pen/ZNNqWw**
I was too lazy to update the doc. 😂 But I'm also considering adding a built-in scroller to make it compatible with the `0.x.y` versions.

**Comment by antivitla** [comment]
Ah, great, thanks! :))
