### ISSUE TITLE
[Tabs] Tabs stack vertically instead of horizontally

### ISSUE THREAD

**Issue by econic** [matsp/material-components-vue#322]
**Describe the bug**
Taking the tabs component straight from the documentation an using it in your example-pin, the tabs stack vertically. Can't find a cause or fix.

**To Reproduce**
Use as in the documentation

**Expected behavior**
Should stack horizontally

**Example**
https://codepen.io/econic/pen/ZdxGGJ

**Comment by tychenjiajun** [comment]
Fixed in #313

**Comment by tychenjiajun** [comment]
This issue seems like a duplicate of #312

**Comment by tychenjiajun** [comment]
After checking the codepen again, I can confirm that this issue is fixed.
