### ISSUE TITLE
[Select] Not handling model value

### ISSUE THREAD

**Issue by Alan-Liang** [matsp/material-components-vue#394]
**Describe the bug**
`<m-select>` is not handling `v-model` passed in.

**To Reproduce**
https://codepen.io/Alan-Liang/pen/LYPZvLz

**Expected behavior**
Label should have 1 default selected.

**Comment by tychenjiajun** [comment]
Thanks for reporting, but I'm struggling with upgrading to the newest versions of the upstream. It may take up to 2 weeks to fix this if I work alone so any PR will be welcomed.
