### ISSUE TITLE
Setters seem to be ill-defined for the LinearProgress.vue component

### ISSUE THREAD

**Issue by ticamacho** [matsp/material-components-vue#43]
Setters are ill-defined for the LinearProgress component, namely on lines 49 and 52.

We have an attempt to set the value of progress and buffer using function calls, while the setters should be using a normal attribution expression.

**Code should be**
- this.mdcLinearProgress.progress = this.progress
- this.mdcLinearProgress.buffer  = this.buffer

**instead of** 
- this.mdcLinearProgress.progress(this.progress)
- this.mdcLinearProgress.buffer(this.buffer)

This leads to an exception being raised and hinders the functionality of the LinearProgress.

**Comment by matsp** [comment]
You are right - looks like the api changed again. Can open a pull request for this change?
