### ISSUE TITLE
Cannot build with webpack

### ISSUE THREAD

**Issue by andrii-trush** [matsp/material-components-vue#49]
```
Failed to compile with 1 errors
 error  in ./node_modules/material-components-vue/components/Theme/Theme.vue
Module build failed: Error: Couldn't find preset "stage-0" relative to directory "D:\\app\\node_modules\\material-components-vue"
```

my js: 

`import MDTheme from 'material-components-vue/components/Theme/Theme.vue'`

**Comment by matsp** [comment]
Can you provide more information what you want to archieve?

**Comment by andrii-trush** [comment]
@matsp Include components to project

**Comment by matsp** [comment]
And you think that providing one line of code and an error message is enough information for me to solve the "problem" ?
