### ISSUE TITLE
 Invalid prop: type check failed when using m-text-field and numbers

### ISSUE THREAD

**Issue by ad-on-is** [matsp/material-components-vue#515]
**Describe the bug**
m-text-field v-model.number not handled correctly and throws error:
`[Vue warn]: Invalid prop: type check failed for prop "value". Expected String with value "0", got Number with value 0.`

**To Reproduce**

ParentComponent.vue
```
<ChildComponent v-for="position in postData.positions" :key="position.id" :position="position" />
```

ChildComponent.vue
```
<m-text-field v-model.number="position.net" type="number" :id="'pg'+position.id">
                    <m-floating-label for="my-text-field">Net/€</m-floating-label>
                    <m-line-ripple slot="bottomLine"/>
                </m-text-field> 

props: {
        position: {
            title:{type: String},
            id: {type: Number},
            net: {type: Number, default:0},
            amount: {type: Number, default: 0},
        },
    },
}
```

**Expected behaviour**
`m-text-field` with `type="text/number/date/...etc"` and `v-model` should work like `<input type="text/number/date/...etc" />`

**Additional context**
Using `<input type="number" v-model.number="position.net" />` works as expected. 
Even if I ommit ` v-model.number` for ` v-model`, it's not working.

**Comment by tychenjiajun** [comment]
@ad-on-is [mdc-web](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield) only supports `string` type value. But it may be a good idea to support number and other input type. I'll investigate.

**Comment by tychenjiajun** [comment]
I'll open a new PR to support `v-model.number`. But personally speaking, I don't recommend you to use `v-model.number` in your case. Your `position.net` may become a `string` instead of a `number` when typing.
Check out this codepen https://codepen.io/chankcccc/pen/abOzQvG and type to type in `1e`, `1e2` or pressing some `backspace` to see what will happen.

**Comment by ad-on-is** [comment]
But what if one needs to do calculations? Omitting .number makes the variable a string, which has always to be converted to float or int. It only becomes string when it's empty.

**Comment by tychenjiajun** [comment]
@ad-on-is No, it will not always be converted to `number`. It might be string sometimes, not just when it's empty. See https://github.com/vuejs/vue/blob/f11449d916a468651d4fd5024c37e3eebbc9941f/src/platforms/web/runtime/modules/dom-props.js#L103, https://github.com/vuejs/vue/blob/6fe07ebf5ab3fea1860c59fe7cdd2ec1b760f9b0/src/shared/util.js#L97 and https://github.com/vuejs/vue/issues/9549
